// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, fs, images, loadski, port, q;

  express = require('express');

  q = require('q');

  fs = require('fs');

  app = express();

  loadski = function(filepath) {
    var deferred;

    deferred = q.defer();
    fs.readFile(filepath, 'utf-8', function(error, text) {
      if (error) {
        return deferred.reject(new Error(error));
      } else {
        return deferred.resolve(text);
      }
    });
    return deferred.promise;
  };

  images = {};

  loadski('json/photos.json').then(function(data) {
    return images = JSON.parse(data).images;
  });

  app.get('/', function(req, res) {
    return loadski('methods.html').then(function(data) {
      return res.end(data);
    });
  });

  app.get('/backend/rest/albums/photos', function(req, res) {
    return loadski('json/photos.json').then(function(data) {
      return res.end(data);
    });
  });

  app.get('/backend/rest/smartshow', function(req, res) {
    return loadski('json/smartshow.json').then(function(data) {
      return res.end(data);
    });
  });

  app.get('/backend/rest/image/retreiveid/:imgid', function(req, res) {
    var filename, url;

    url = images[req.params.imgid].src;
    filename = url.substr(url.lastIndexOf('/') + 1);
    return res.sendfile('photos/' + filename);
  });

  port = process.env.PORT || 5000;

  console.log('listening on ' + port);

  app.listen(port);

}).call(this);
